[package]
name = "skype"
version = "0.1.0"
edition = "2021"

[dependencies]
image.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
